### ISSUE TITLE
[BUG] 第二章第一个例子跑不通

### ISSUE THREAD

**Issue by ScGPS** [ikcamp/Koa-Node.js-Web-FE-Development#5]
```
var express = require('express');
var app=express();
var hostname = '127.0.0.1';
var port = 3000;
app.get('/',function(req,res){
    asyncFunction1(params, function(){
        asyncFunction2(params, function(){
            asyncFunction3(params, function(){
                res.send('Hello World!');
            });
        });
    });
});
var server = app.listen(3000);
console.log(`Server running at http://${hostname}:${port}/`);
```
运行后，访问 http://127.0.0.1:3000/ 报错
```
C:\Program Files\nodejs\node.exe' --nolazy --debug-brk=49936 index_express.js
Debugger listening on [::]:49936
Server running at http://127.0.0.1:3000/
ReferenceError: asyncFunction1 is not defined
    at d:\Code\nodejs_test\koa2_002\index_express.js:6:5
    at Layer.handle [as handle_request] (d:\Code\nodejs_test\koa2_002\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\Code\nodejs_test\koa2_002\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (d:\Code\nodejs_test\koa2_002\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\Code\nodejs_test\koa2_002\node_modules\express\lib\router\layer.js:95:5)
    at d:\Code\nodejs_test\koa2_002\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (d:\Code\nodejs_test\koa2_002\node_modules\express\lib\router\index.js:335:12)
    at next (d:\Code\nodejs_test\koa2_002\node_modules\express\lib\router\index.js:275:10)
    at expressInit (d:\Code\nodejs_test\koa2_002\node_modules\express\lib\middleware\init.js:40:5)
    at Layer.handle [as handle_request] (d:\Code\nodejs_test\koa2_002\node_modules\express\lib\router\layer.js:95:5)
```

**Comment by ScGPS** [comment]
我用了nvm安装node
```
nvm use 11.13.0
node --version

nvm use 6.10.2
node --version

nvm use 8.1.4
node --version

nvm use 10.15.3
node --version
```
这几个node版本都报错。能麻烦看看是哪里的问题么？

**Comment by xiaoyaojun** [comment]
抱歉，看了下你node版本装过最新的了。但是从你的报错来看，你好像用的是express框架是吗？这个例子是基于koa2的


| |
Tony
|
|
邮箱：gjnjit@163.com
|

Signature is customized by Netease Mail Master

在2019年04月21日 12:51，ScGPS 写道：

我用了nvm安装node

nvm use 11.13.0

node --version



nvm use 6.10.2

node --version



nvm use 8.1.4

node --version



nvm use 10.15.3

node --version



这几个node版本都报错。能麻烦看看是哪里的问题么？

**Comment by ScGPS** [comment]
书上P27页，就是有对比试验，是Express啊。你看看呢？

**Comment by ScGPS** [comment]
```
var express = require('express');
var app=express();
var promise = require('promise');
var hostname = '127.0.0.1';
var port = 3000;
var asyncFunction1=()=> new promise((resolve, reject)=> setTimeout(()=>resolve('test1'), 3000));
var asyncFunction2=()=> new promise((resolve, reject)=> setTimeout(()=>resolve('test2'), 3000));
var asyncFunction3=()=> new promise((resolve, reject)=> setTimeout(()=>resolve('test3'), 3000));
app.get('/',function(req,res){
    asyncFunction1(function(){
        asyncFunction2(function(){
            asyncFunction3(function(){
                res.send('Hello World!');
            });
        });
    });
});
var server = app.listen(3000);
console.log(`Server(Express) running at http://${hostname}:${port}/`);
```
这个不行，能改进一下么？谢谢！

**Comment by xiaoyaojun** [comment]
这里的异步函数是通过回调函数来处理的，把promise去掉，增加一个callback回调函数的参数，然后在setTimeout中调用这个callback。你先试试，如果不行，明天我给你详细例子。

**Comment by ScGPS** [comment]
明天给我个例子吧。读着感觉很复杂啊。

**Comment by dail** [comment]
看上去，这个代码不是示例代码，这个只是告诉你说express是通过回调的方式来处理的，所谓的asyncFunction1，是第一个一步回调函数，是需要另外定义的。在你贴出的代码中并未定义这个函数，因此代码无法运行，你可以定义为
`function asyncFunction1 (params, callback){
     console.log(params)
    callback()
}`

**Comment by ScGPS** [comment]
```
var express = require('express');
var app = express();
var hostname = '127.0.0.1';
var port = 3000;

function asyncFunction1(params, callback) {
    console.log(params);
    callback();
}

function asyncFunction2(params, callback) {
    console.log(params);
    callback();
}

function asyncFunction3(params, callback) {
    console.log(params);
    callback();
}

app.get('/', function(req, res) {
    asyncFunction1("asyncFunction1", function() {
        asyncFunction2("asyncFunction2", function() {
            asyncFunction3("asyncFunction3", function() {
                res.send('Hello World!');
            });
        });
    });
});
var server = app.listen(3000);
console.log(`Server(Express) running at http://${hostname}:${port}/`);
```
运行后，访问 http://127.0.0.1:3000/
页面输出:
```
Hello World!
```

后台输出:
```
...
Server(Express) running at http://127.0.0.1:3000/
index_express.js:32
asyncFunction1
index_express.js:8
asyncFunction2
index_express.js:13
asyncFunction3
```

**Comment by ScGPS** [comment]
@dail 谢谢!我依据你的代码，改了改，就可以用了。谢谢！
