### ISSUE TITLE
[BUG] 第二章第二个例子跑不通

### ISSUE THREAD

**Issue by ScGPS** [ikcamp/Koa-Node.js-Web-FE-Development#6]
```
var koa= require('koa');
var app = new koa();
var hostname = '127.0.0.1';
var port = 3000;
app.use(function*(){
    yield asyncFunction1(params);
    yield asyncFunction2(params);
    yield asyncFunction3(params);
    this.body='Hello World!'    
});
var server = app.listen(port);
console.log(`Server(Koa) running at http://${hostname}:${port}/`);
```
运行后 访问 http://127.0.0.1:3000/ 报错报错
```
ReferenceError: asyncFunction1 is not defined
      at Object.<anonymous> (d:\Code\nodejs_test\koa2_002\index_koa.js:6:5)
      at Generator.next (<anonymous>)
      at onFulfilled (d:\Code\nodejs_test\koa2_002\node_modules\co\index.js:65:19)
      at d:\Code\nodejs_test\koa2_002\node_modules\co\index.js:54:5
      at new Promise (<anonymous>)
      at Object.co (d:\Code\nodejs_test\koa2_002\node_modules\co\index.js:50:10)
      at converted (d:\Code\nodejs_test\koa2_002\node_modules\koa-convert\index.js:17:15)
      at dispatch (d:\Code\nodejs_test\koa2_002\node_modules\koa-compose\index.js:42:32)
      at d:\Code\nodejs_test\koa2_002\node_modules\koa-compose\index.js:34:12
      at Application.handleRequest (d:\Code\nodejs_test\koa2_002\node_modules\koa\lib\application.js:151:12)
application.js:190
```

**Comment by ScGPS** [comment]
```
var koa= require('koa');
var app = new koa();
var promise = require('promise');
var hostname = '127.0.0.1';
var port = 3000;
var asyncFunction1=()=> new promise((resolve, reject)=> setTimeout(()=>resolve('test1'), 3000));
var asyncFunction2=()=> new promise((resolve, reject)=> setTimeout(()=>resolve('test2'), 3000));
var asyncFunction3=()=> new promise((resolve, reject)=> setTimeout(()=>resolve('test3'), 3000));
app.use(function*(){
    yield asyncFunction1();
    yield asyncFunction2();
    yield asyncFunction3();
    this.body='Hello World!'    
});
var server = app.listen(port);
console.log(`Server(Koa) running at http://${hostname}:${port}/`);
```
访问http://127.0.0.1:3000/ 可以得到
```
Hello World!
```
