### ISSUE TITLE
[BUG] 第二章第三个例子跑不通

### ISSUE THREAD

**Issue by ScGPS** [ikcamp/Koa-Node.js-Web-FE-Development#7]
```
const koa = require('koa');
const app = new koa();
const hostname = '127.0.0.1';
const port = 3000;
app.use(async ctx=>{
    await asyncFunction1(params);
    await asyncFunction2(params);
    await asyncFunction3(params);
    ctx.body='Hello World!';
});
app.listen(port);
console.log(`Server(Koa2) running at http://${hostname}:${port}/`);
```
访问 http://127.0.0.1:3000/ 报错
```
ReferenceError: asyncFunction1 is not defined
      at app.use (d:\Code\nodejs_test\koa2_002\index_koa2.js:6:5)
      at dispatch (d:\Code\nodejs_test\koa2_002\node_modules\koa-compose\index.js:42:32)
      at d:\Code\nodejs_test\koa2_002\node_modules\koa-compose\index.js:34:12
      at Application.handleRequest (d:\Code\nodejs_test\koa2_002\node_modules\koa\lib\application.js:151:12)
      at Server.handleRequest (d:\Code\nodejs_test\koa2_002\node_modules\koa\lib\application.js:133:19)
      at Server.emit (events.js:193:13)
      at parserOnIncoming (_http_server.js:680:12)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:113:17)
application.js:190
  ReferenceError: asyncFunction1 is not defined
      at app.use (d:\Code\nodejs_test\koa2_002\index_koa2.js:6:5)
      at dispatch (d:\Code\nodejs_test\koa2_002\node_modules\koa-compose\index.js:42:32)
      at d:\Code\nodejs_test\koa2_002\node_modules\koa-compose\index.js:34:12
      at Application.handleRequest (d:\Code\nodejs_test\koa2_002\node_modules\koa\lib\application.js:151:12)
      at Server.handleRequest (d:\Code\nodejs_test\koa2_002\node_modules\koa\lib\application.js:133:19)
      at Server.emit (events.js:193:13)
      at parserOnIncoming (_http_server.js:680:12)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:113:17)
```

**Comment by xiaoyaojun** [comment]
这是因为你的node版本太低了哦，所以不支持await和async语法糖，试试最新的node版本吧😄


| |
Tony
|
|
邮箱：gjnjit@163.com
|

Signature is customized by Netease Mail Master

在2019年04月21日 19:29，ScGPS 写道：
const koa = require('koa');

const app = new koa();

const hostname = '127.0.0.1';

const port = 3000;

app.use(async ctx=>{

    await asyncFunction1(params);

    await asyncFunction2(params);

    await asyncFunction3(params);

    ctx.body='Hello World!';

});

app.listen(port);

console.log(`Server(Koa2) running at http://${hostname}:${port}/`);



访问 http://127.0.0.1:3000/ 报错

ReferenceError: asyncFunction1 is not defined

      at app.use (d:\Code\nodejs_test\koa2_002\index_koa2.js:6:5)

      at dispatch (d:\Code\nodejs_test\koa2_002\node_modules\koa-compose\index.js:42:32)

      at d:\Code\nodejs_test\koa2_002\node_modules\koa-compose\index.js:34:12

      at Application.handleRequest (d:\Code\nodejs_test\koa2_002\node_modules\koa\lib\application.js:151:12)

      at Server.handleRequest (d:\Code\nodejs_test\koa2_002\node_modules\koa\lib\application.js:133:19)

      at Server.emit (events.js:193:13)

      at parserOnIncoming (_http_server.js:680:12)

      at HTTPParser.parserOnHeadersComplete (_http_common.js:113:17)

application.js:190

  ReferenceError: asyncFunction1 is not defined

      at app.use (d:\Code\nodejs_test\koa2_002\index_koa2.js:6:5)

      at dispatch (d:\Code\nodejs_test\koa2_002\node_modules\koa-compose\index.js:42:32)

      at d:\Code\nodejs_test\koa2_002\node_modules\koa-compose\index.js:34:12

      at Application.handleRequest (d:\Code\nodejs_test\koa2_002\node_modules\koa\lib\application.js:151:12)

      at Server.handleRequest (d:\Code\nodejs_test\koa2_002\node_modules\koa\lib\application.js:133:19)

      at Server.emit (events.js:193:13)

      at parserOnIncoming (_http_server.js:680:12)

      at HTTPParser.parserOnHeadersComplete (_http_common.js:113:17)

**Comment by ScGPS** [comment]
我增加了node.js版本信息的输出，已经是最新版本了。
你试试吧。
```
const koa = require('koa');
const app = new koa();
const process = require('process');
const hostname = '127.0.0.1';
const port = 3000;
app.use(async ctx=>{
    await asyncFunction1(params);
    await asyncFunction2(params);
    await asyncFunction3(params);
    ctx.body='Hello World!';
});
app.listen(port);
console.log(`Version: ${process.version}`);
console.log(`Server(Koa2) running at http://${hostname}:${port}/`);
```

报错信息
```
Debugger listening o
n ws://127.0.0.1:23825/b2a98b62-4122-45e6-9302-bab395bcf79a
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Version: v11.13.0
index_koa2.js:13
Server(Koa2) running at http://127.0.0.1:3000/
  ReferenceError: asyncFunction1 is not defined
      at app.use (d:\Code\nodejs_test\koa2_002\index_koa2.js:7:5)
      at dispatch (d:\Code\nodejs_test\koa2_002\node_modules\koa-compose\index.js:42:32)
      at d:\Code\nodejs_test\koa2_002\node_modules\koa-compose\index.js:34:12
      at Application.handleRequest (d:\Code\nodejs_test\koa2_002\node_modules\koa\lib\application.js:151:12)
      at Server.handleRequest (d:\Code\nodejs_test\koa2_002\node_modules\koa\lib\application.js:133:19)
      at Server.emit (events.js:193:13)
      at parserOnIncoming (_http_server.js:680:12)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:113:17)
application.js:190
  ReferenceError: asyncFunction1 is not defined
      at app.use (d:\Code\nodejs_test\koa2_002\index_koa2.js:7:5)
      at dispatch (d:\Code\nodejs_test\koa2_002\node_modules\koa-compose\index.js:42:32)
      at d:\Code\nodejs_test\koa2_002\node_modules\koa-compose\index.js:34:12
      at Application.handleRequest (d:\Code\nodejs_test\koa2_002\node_modules\koa\lib\application.js:151:12)
      at Server.handleRequest (d:\Code\nodejs_test\koa2_002\node_modules\koa\lib\application.js:133:19)
      at Server.emit (events.js:193:13)
      at parserOnIncoming (_http_server.js:680:12)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:113:17)
```

**Comment by xiaoyaojun** [comment]
你好，我认真看了一下，确实是对比。这里的几个例子都省略了asyncFunction的具体定义，类似于伪代码的演示。要跑通代码，可以自己定义一个具体的异步函数，比如执行一个setTimeout，就可以了。

**Comment by xiaoyaojun** [comment]
比如const promiseRes=()=> new promise((resolve, reject)=> setTimeout(()=>resolve(‘test’), 3000)).然后用这个promiseRes替换asyncFunction

**Comment by ScGPS** [comment]
代码可以了。不过这个函数好复杂啊，能否改成简单的版本,包含console.log信息么？能否提供一个简单函数定义，满足这3个例子？谢谢！
```
const koa = require('koa');
const app = new koa();
const process = require('process');
const promise = require('promise');
const hostname = '127.0.0.1';
const port = 3000;
const asyncFunction1=()=> new promise((resolve, reject)=> setTimeout(()=>resolve('test1'), 3000));
const asyncFunction2=()=> new promise((resolve, reject)=> setTimeout(()=>resolve('test2'), 3000));
const asyncFunction3=()=> new promise((resolve, reject)=> setTimeout(()=>resolve('test3'), 3000));
app.use(async ctx=>{
    await asyncFunction1();
    await asyncFunction2();
    await asyncFunction3();
    ctx.body='Hello World!';
});
app.listen(port);
console.log(`Version: ${process.version}`);
console.log(`Server(Koa2) running at http://${hostname}:${port}/`);
```
访问http://127.0.0.1:3000/ 可以得到
```
Hello World!
```

**Comment by xiaoyaojun** [comment]
这个已经算是最简单的异步函数的例子啦，你可以把公共部分提取出来。在真实开发中，这个asyncFunction一般是一个请求的api或者某I/O操作，又或者是一个中间件的调用

**Comment by ScGPS** [comment]
express, koa 里面的函数定义能给一个么？初学啊。

**Comment by ScGPS** [comment]
谢谢！
